# SITE CONFIGURATION
baseurl: ""
url: "https://javagruppen.github.io"
title: Javagruppen # site's title
description: "Dansk Java User-group" # used by search engines

excerpt_separator: "<!-- more -->"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title:  # blog's title
  avatar: assets/img/logo.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Javagruppen er Danmarks <code>Java User Group</code> <br> - en brugergruppe om alt, Java-relateret.</p>
  header_text_feature_image: assets/img/topbanner.jpg
  footer_text: >
    Alle rettigheder tilhører Javagruppen.

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "javagruppen"
  flickr:
  gitlab:
  github: "javagruppen"
  google_plus:
  instagram:
  keybase:
  linkedin: "https://www.linkedin.com/groups/36020/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: javagruppen
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Følg"
  str_rss_follow: "Følg RSS feed"
  str_email: "E-mail"
  str_next_post: "Næste artikel"
  str_previous_post: "Forrige artikel"
  str_next_page: "Næste"
  str_previous_page: "Forrige"
  str_continue_reading: "Læs mere"
  str_javascript_required_disqus: "Aktiver JavaScript for at læse kommentarer."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 10
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  emails:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", ".idea/"]
